<?php

use App\Models\Buyer;


function getRoleName($role_id){
   switch ($role_id){
        case "1":
            echo "SuperAdmin";
            break;
        case "2":
            echo "Admin";
            break;
        case "3":
            echo "Employee";
            break;
        default:
            echo "Guest";
   }
}

function getCurrency(){
    return [
        'USD' => 'United States Dollar',
        'EUR' => 'Euro',
        // 'JPY' => 'Japanese Yen',
        // 'GBP' => 'British Pound Sterling',
        // 'AUD' => 'Australian Dollar',
        // 'CAD' => 'Canadian Dollar',
        // 'CHF' => 'Swiss Franc',
        // 'CNY' => 'Chinese Yuan',
        // 'SEK' => 'Swedish Krona',
        // 'NZD' => 'New Zealand Dollar',
        // 'MXN' => 'Mexican Peso',
        // 'SGD' => 'Singapore Dollar',
        // 'HKD' => 'Hong Kong Dollar',
        // 'NOK' => 'Norwegian Krone',
        // 'KRW' => 'South Korean Won',
        // 'TRY' => 'Turkish Lira',
        'RUB' => 'Russian Ruble',
        'INR' => 'Indian Rupee',
        // 'BRL' => 'Brazilian Real',
        // 'ZAR' => 'South African Rand',
        // 'DKK' => 'Danish Krone',
        // 'PLN' => 'Polish Zloty',
        // 'THB' => 'Thai Baht',
        // 'IDR' => 'Indonesian Rupiah',
        // 'HUF' => 'Hungarian Forint',
        // 'CZK' => 'Czech Koruna',
        // 'ILS' => 'Israeli New Shekel',
        // 'MYR' => 'Malaysian Ringgit',
        // 'PHP' => 'Philippine Peso',
        // 'TWD' => 'New Taiwan Dollar',
        // 'SAR' => 'Saudi Riyal',
        // 'AED' => 'United Arab Emirates Dirham',
        // 'ARS' => 'Argentine Peso',
        // 'CLP' => 'Chilean Peso',
        // 'COP' => 'Colombian Peso',
        // 'PEN' => 'Peruvian Sol',
        // 'PKR' => 'Pakistani Rupee',
        // 'VND' => 'Vietnamese Dong',
        // 'EGP' => 'Egyptian Pound',
        // 'NGN' => 'Nigerian Naira',
        // 'KZT' => 'Kazakhstani Tenge',
        // 'BDT' => 'Bangladeshi Taka',
        // 'QAR' => 'Qatari Riyal',
        // 'KWD' => 'Kuwaiti Dinar',
        // 'LKR' => 'Sri Lankan Rupee',
        // 'MMK' => 'Burmese Kyat',
        // 'MAD' => 'Moroccan Dirham',
        // 'DZD' => 'Algerian Dinar',
        // 'GHS' => 'Ghanaian Cedi',
        // 'JMD' => 'Jamaican Dollar',
        // 'BHD' => 'Bahraini Dinar',
        // 'OMR' => 'Omani Rial',
        // 'RSD' => 'Serbian Dinar',
        // 'BGN' => 'Bulgarian Lev',
        // 'HRK' => 'Croatian Kuna',
        // 'ISK' => 'Icelandic Krona',
        // 'XOF' => 'West African CFA Franc',
        // 'XAF' => 'Central African CFA Franc',
        // 'AFN' => 'Afghan Afghani',
        // 'ALL' => 'Albanian Lek',
        // 'AMD' => 'Armenian Dram',
        // 'AOA' => 'Angolan Kwanza',
        // 'AWG' => 'Aruban Florin',
        // 'AZN' => 'Azerbaijani Manat',
        // 'BAM' => 'Bosnia-Herzegovina Convertible Mark',
        // 'BBD' => 'Barbadian Dollar',
        // 'BIF' => 'Burundian Franc',
        // 'BMD' => 'Bermudian Dollar',
        // 'BND' => 'Brunei Dollar',
        // 'BOB' => 'Bolivian Boliviano',
        // 'BSD' => 'Bahamian Dollar',
        // 'BTN' => 'Bhutanese Ngultrum',
        // 'BWP' => 'Botswana Pula',
        // 'BYN' => 'Belarusian Ruble',
        // 'BZD' => 'Belize Dollar',
        // 'CDF' => 'Congolese Franc',
        // 'CUP' => 'Cuban Peso',
        // 'CVE' => 'Cape Verdean Escudo',
        // 'DJF' => 'Djiboutian Franc',
        // 'DOP' => 'Dominican Peso',
        // 'ERN' => 'Eritrean Nakfa',
        // 'ETB' => 'Ethiopian Birr',
        // 'FJD' => 'Fijian Dollar',
        // 'FKP' => 'Falkland Islands Pound',
        // 'FOK' => 'Faroese Króna',
        // 'GEL' => 'Georgian Lari',
        // 'GIP' => 'Gibraltar Pound',
        // 'GTQ' => 'Guatemalan Quetzal',
        // 'GYD' => 'Guyanese Dollar',
        // 'HTG' => 'Haitian Gourde',
        // 'IQD' => 'Iraqi Dinar',
        // 'IRR' => 'Iranian Rial',
        // 'JOD' => 'Jordanian Dinar',
        // 'KES' => 'Kenyan Shilling',
        // 'KGS' => 'Kyrgyzstani Som',
        // 'KMF' => 'Comorian Franc',
        // 'KYD' => 'Cayman Islands Dollar',
        // 'LAK' => 'Lao Kip',
        // 'LBP' => 'Lebanese Pound',
        // 'LSL' => 'Lesotho Loti',
        // 'LYD' => 'Libyan Dinar',
        // 'MGA' => 'Malagasy Ariary',
        // 'MKD' => 'Macedonian Denar',
        // 'MNT' => 'Mongolian Tögrög',
        // 'MOP' => 'Macanese Pataca',
        // 'MRU' => 'Mauritanian Ouguiya',
        // 'MUR' => 'Mauritian Rupee',
        // 'MWK' => 'Malawian Kwacha',
        // 'MZN' => 'Mozambican Metical',
        // 'NAD' => 'Namibian Dollar',
        // 'NPR' => 'Nepalese Rupee',
        // 'PGK' => 'Papua New Guinean Kina',
        // 'PYG' => 'Paraguayan Guaraní',
        // 'RON' => 'Romanian Leu',
        // 'SBD' => 'Solomon Islands Dollar',
        // 'SCR' => 'Seychellois Rupee',
        // 'SHP' => 'Saint Helena Pound',
        // 'SLL' => 'Sierra Leonean Leone',
        // 'SOS' => 'Somali Shilling',
        // 'SSP' => 'South Sudanese Pound',
        // 'STN' => 'São Tomé and Príncipe Dobra',
        // 'SYP' => 'Syrian Pound',
        // 'SZL' => 'Eswatini Lilangeni',
        // 'TJS' => 'Tajikistani Somoni',
        // 'TMT' => 'Turkmenistani Manat',
        // 'TOP' => 'Tongan Paʻanga',
        // 'TTD' => 'Trinidad and Tobago Dollar',
        // 'TZS' => 'Tanzanian Shilling',
        // 'UGX' => 'Ugandan Shilling',
        // 'UYU' => 'Uruguayan Peso',
        // 'UZS' => 'Uzbekistani Soʻm',
        // 'VES' => 'Venezuelan Bolívar Soberano',
        // 'WST' => 'Samoan Tālā',
        // 'XCD' => 'East Caribbean Dollar',
        // 'YER' => 'Yemeni Rial',
        // 'ZMW' => 'Zambian Kwacha',
        // 'ZWL' => 'Zimbabwean Dollar',
        // Add more currencies as needed
    ];

}

function getCountry(){
  return  [
            // 'AF' => 'Afghanistan',
            // 'AL' => 'Albania',
            // 'DZ' => 'Algeria',
            // 'AD' => 'Andorra',
            // 'AO' => 'Angola',
            // 'AG' => 'Antigua and Barbuda',
            // 'AR' => 'Argentina',
            // 'AM' => 'Armenia',
            // 'AU' => 'Australia',
            // 'AT' => 'Austria',
            // 'AZ' => 'Azerbaijan',
            // 'BS' => 'Bahamas',
            // 'BH' => 'Bahrain',
            // 'BD' => 'Bangladesh',
            // 'BB' => 'Barbados',
            // 'BY' => 'Belarus',
            // 'BE' => 'Belgium',
            // 'BZ' => 'Belize',
            // 'BJ' => 'Benin',
            // 'BT' => 'Bhutan',
            // 'BO' => 'Bolivia',
            // 'BA' => 'Bosnia and Herzegovina',
            // 'BW' => 'Botswana',
            // 'BR' => 'Brazil',
            // 'BN' => 'Brunei',
            // 'BG' => 'Bulgaria',
            // 'BF' => 'Burkina Faso',
            // 'BI' => 'Burundi',
            // 'CV' => 'Cabo Verde',
            // 'KH' => 'Cambodia',
            // 'CM' => 'Cameroon',
            // 'CA' => 'Canada',
            // 'CF' => 'Central African Republic',
            // 'TD' => 'Chad',
            // 'CL' => 'Chile',
            // 'CN' => 'China',
            // 'CO' => 'Colombia',
            // 'KM' => 'Comoros',
            // 'CG' => 'Congo',
            // 'CD' => 'Congo, Democratic Republic of the',
            // 'CR' => 'Costa Rica',
            // 'CI' => 'Cote d\'Ivoire',
            // 'HR' => 'Croatia',
            // 'CU' => 'Cuba',
            // 'CY' => 'Cyprus',
            // 'CZ' => 'Czech Republic',
            // 'DK' => 'Denmark',
            // 'DJ' => 'Djibouti',
            // 'DM' => 'Dominica',
            // 'DO' => 'Dominican Republic',
            // 'EC' => 'Ecuador',
            // 'EG' => 'Egypt',
            // 'SV' => 'El Salvador',
            // 'GQ' => 'Equatorial Guinea',
            // 'ER' => 'Eritrea',
            // 'EE' => 'Estonia',
            // 'SZ' => 'Eswatini',
            // 'ET' => 'Ethiopia',
            // 'FJ' => 'Fiji',
            // 'FI' => 'Finland',
            // 'FR' => 'France',
            // 'GA' => 'Gabon',
            // 'GM' => 'Gambia',
            // 'GE' => 'Georgia',
            // 'DE' => 'Germany',
            // 'GH' => 'Ghana',
            // 'GR' => 'Greece',
            // 'GD' => 'Grenada',
            // 'GT' => 'Guatemala',
            // 'GN' => 'Guinea',
            // 'GW' => 'Guinea-Bissau',
            // 'GY' => 'Guyana',
            // 'HT' => 'Haiti',
            // 'HN' => 'Honduras',
            // 'HU' => 'Hungary',
            // 'IS' => 'Iceland',
            'IN' => 'India',
            // 'ID' => 'Indonesia',
            // 'IR' => 'Iran',
            // 'IQ' => 'Iraq',
            // 'IE' => 'Ireland',
            // 'IL' => 'Israel',
            // 'IT' => 'Italy',
            // 'JM' => 'Jamaica',
            // 'JP' => 'Japan',
            // 'JO' => 'Jordan',
            // 'KZ' => 'Kazakhstan',
            // 'KE' => 'Kenya',
            // 'KI' => 'Kiribati',
            // 'KP' => 'Korea, North',
            // 'KR' => 'Korea, South',
            // 'KW' => 'Kuwait',
            // 'KG' => 'Kyrgyzstan',
            // 'LA' => 'Laos',
            // 'LV' => 'Latvia',
            // 'LB' => 'Lebanon',
            // 'LS' => 'Lesotho',
            // 'LR' => 'Liberia',
            // 'LY' => 'Libya',
            // 'LI' => 'Liechtenstein',
            // 'LT' => 'Lithuania',
            // 'LU' => 'Luxembourg',
            // 'MG' => 'Madagascar',
            // 'MW' => 'Malawi',
            // 'MY' => 'Malaysia',
            // 'MV' => 'Maldives',
            // 'ML' => 'Mali',
            // 'MT' => 'Malta',
            // 'MH' => 'Marshall Islands',
            // 'MR' => 'Mauritania',
            // 'MU' => 'Mauritius',
            // 'MX' => 'Mexico',
            // 'FM' => 'Micronesia',
            // 'MD' => 'Moldova',
            // 'MC' => 'Monaco',
            // 'MN' => 'Mongolia',
            // 'ME' => 'Montenegro',
            // 'MA' => 'Morocco',
            // 'MZ' => 'Mozambique',
            // 'MM' => 'Myanmar',
            // 'NA' => 'Namibia',
            // 'NR' => 'Nauru',
            // 'NP' => 'Nepal',
            // 'NL' => 'Netherlands',
            // 'NZ' => 'New Zealand',
            // 'NI' => 'Nicaragua',
            // 'NE' => 'Niger',
            // 'NG' => 'Nigeria',
            // 'MK' => 'North Macedonia',
            // 'NO' => 'Norway',
            // 'OM' => 'Oman',
            // 'PK' => 'Pakistan',
            // 'PW' => 'Palau',
            // 'PA' => 'Panama',
            // 'PG' => 'Papua New Guinea',
            // 'PY' => 'Paraguay',
            // 'PE' => 'Peru',
            // 'PH' => 'Philippines',
            // 'PL' => 'Poland',
            // 'PT' => 'Portugal',
            // 'QA' => 'Qatar',
            // 'RO' => 'Romania',
            // 'RU' => 'Russia',
            // 'RW' => 'Rwanda',
            // 'KN' => 'Saint Kitts and Nevis',
            // 'LC' => 'Saint Lucia',
            // 'VC' => 'Saint Vincent and the Grenadines',
            // 'WS' => 'Samoa',
            // 'SM' => 'San Marino',
            // 'ST' => 'Sao Tome and Principe',
            // 'SA' => 'Saudi Arabia',
            // 'SN' => 'Senegal',
            // 'RS' => 'Serbia',
            // 'SC' => 'Seychelles',
            // 'SL' => 'Sierra Leone',
            // 'SG' => 'Singapore',
            // 'SK' => 'Slovakia',
            // 'SI' => 'Slovenia',
            // 'SB' => 'Solomon Islands',
            // 'SO' => 'Somalia',
            // 'ZA' => 'South Africa',
            // 'SS' => 'South Sudan',
            // 'ES' => 'Spain',
            // 'LK' => 'Sri Lanka',
            // 'SD' => 'Sudan',
            // 'SR' => 'Suriname',
            // 'SE' => 'Sweden',
            // 'CH' => 'Switzerland',
            // 'SY' => 'Syria',
            // 'TW' => 'Taiwan',
            // 'TJ' => 'Tajikistan',
            // 'TZ' => 'Tanzania',
            // 'TH' => 'Thailand',
            // 'TL' => 'Timor-Leste',
            // 'TG' => 'Togo',
            // 'TO' => 'Tonga',
            // 'TT' => 'Trinidad and Tobago',
            // 'TN' => 'Tunisia',
            // 'TR' => 'Turkey',
            // 'TM' => 'Turkmenistan',
            // 'TV' => 'Tuvalu',
            // 'UG' => 'Uganda',
            // 'UA' => 'Ukraine',
            // 'AE' => 'United Arab Emirates',
            // 'GB' => 'United Kingdom',
            'US' => 'United States',
            // 'UY' => 'Uruguay',
            // 'UZ' => 'Uzbekistan',
            // 'VU' => 'Vanuatu',
            // 'VA' => 'Vatican City',
            // 'VE' => 'Venezuela',
            // 'VN' => 'Vietnam',
            // 'YE' => 'Yemen',
            // 'ZM' => 'Zambia',
            // 'ZW' => 'Zimbabwe'
    ];
}

function getBuyersName(){
    return Buyer::select('buyer_name')->get();
}

function getRack_no(){
    return  ['RACK F1',
'RACK F2',
'RACK F3'];
}
